version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: "maven"
    # Look for pom.xml and parent/child pom.xml files in root directory
    directory: "/"
    # Check for updates daily at 9am UTC
    schedule:
      interval: "daily"
      time: "09:00"
    # Allow up to 5 open pull requests for Maven dependencies
    open-pull-requests-limit: 5
    # Add reviewers
    reviewers:
      - "devops-thiago"
    # Add assignees
    assignees:
      - "devops-thiago"
    # Customize commit messages
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group all patch updates into a single PR
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    # Allow both direct and indirect dependencies
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"